//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineClearingEvaluatorIntegrationTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MineClearingEvaluatorIntegrationTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z.
        /// </summary>
        internal static string FieldFile1 {
            get {
                return ResourceManager.GetString("FieldFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..Z..
        ///.....
        ///Z...Z
        ///.....
        ///..Z...
        /// </summary>
        internal static string FieldFile2 {
            get {
                return ResourceManager.GetString("FieldFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z.
        /// </summary>
        internal static string FieldFile3 {
            get {
                return ResourceManager.GetString("FieldFile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..a..
        ///.....
        ///.....
        ///.....
        ///..a...
        /// </summary>
        internal static string FieldFile4 {
            get {
                return ResourceManager.GetString("FieldFile4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..Z..
        ///.....
        ///Z...Z
        ///.....
        ///..Z...
        /// </summary>
        internal static string FieldFile5 {
            get {
                return ResourceManager.GetString("FieldFile5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1
        ///
        ///z
        ///
        ///gamma
        ///
        ///.
        ///
        ///pass (5).
        /// </summary>
        internal static string Output1 {
            get {
                return ResourceManager.GetString("Output1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1
        ///
        ///..Z..
        ///.....
        ///Z...Z
        ///.....
        ///..Z..
        ///
        ///north
        ///
        ///.....
        ///.....
        ///..Y..
        ///.....
        ///Y...Y
        ///.....
        ///..Y..
        ///
        ///Step 2
        ///
        ///.....
        ///.....
        ///..Y..
        ///.....
        ///Y...Y
        ///.....
        ///..Y..
        ///
        ///delta south
        ///
        ///.....
        ///.....
        ///X...X
        ///.....
        ///..X..
        ///
        ///Step 3
        ///
        ///.....
        ///.....
        ///X...X
        ///.....
        ///..X..
        ///
        ///west
        ///
        ///.......
        ///.......
        ///..W...W
        ///.......
        ///....W..
        ///
        ///Step 4
        ///
        ///.......
        ///.......
        ///..W...W
        ///.......
        ///....W..
        ///
        ///gamma east
        ///
        ///.....
        ///.....
        ///....V
        ///.....
        ///..V..
        ///
        ///Step 5
        ///.....
        ///.....
        ///....V
        ///.....
        ///..V..
        ///
        ///east
        ///
        ///...
        ///...
        ///..U
        ///...
        ///U..
        ///
        ///St [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Output2 {
            get {
                return ResourceManager.GetString("Output2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1
        ///
        ///z
        ///
        ///gamma
        ///
        ///.
        ///
        ///pass (1).
        /// </summary>
        internal static string Output3 {
            get {
                return ResourceManager.GetString("Output3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1
        ///
        ///a
        ///.
        ///.
        ///.
        ///a
        ///
        ///north
        ///
        ///.
        ///.
        ///*
        ///.
        ///.
        ///.
        ///*
        ///
        ///fail (0).
        /// </summary>
        internal static string Output4 {
            get {
                return ResourceManager.GetString("Output4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1
        ///
        ///..Z..
        ///.....
        ///Z...Z
        ///.....
        ///..Z..
        ///
        ///north
        ///
        ///.....
        ///.....
        ///..Y..
        ///.....
        ///Y...Y
        ///.....
        ///..Y..
        ///
        ///Step 2
        ///
        ///.....
        ///.....
        ///..Y..
        ///.....
        ///Y...Y
        ///.....
        ///..Y..
        ///
        ///delta south
        ///
        ///.....
        ///.....
        ///X...X
        ///.....
        ///..X..
        ///
        ///Step 3
        ///
        ///.....
        ///.....
        ///X...X
        ///.....
        ///..X..
        ///
        ///west
        ///
        ///.......
        ///.......
        ///..W...W
        ///.......
        ///....W..
        ///
        ///Step 4
        ///
        ///.......
        ///.......
        ///..W...W
        ///.......
        ///....W..
        ///
        ///gamma east
        ///
        ///.....
        ///.....
        ///....V
        ///.....
        ///..V..
        ///
        ///Step 5
        ///
        ///.....
        ///.....
        ///....V
        ///.....
        ///..V..
        ///
        ///east
        ///
        ///...
        ///...
        ///..U
        ///...
        ///U..
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Output5 {
            get {
                return ResourceManager.GetString("Output5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gamma.
        /// </summary>
        internal static string ScriptFile1 {
            get {
                return ResourceManager.GetString("ScriptFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north
        ///delta south
        ///west
        ///gamma east
        ///east
        ///gamma west
        ///south
        ///delta.
        /// </summary>
        internal static string ScriptFile2 {
            get {
                return ResourceManager.GetString("ScriptFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gamma
        ///north alpha.
        /// </summary>
        internal static string ScriptFile3 {
            get {
                return ResourceManager.GetString("ScriptFile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north
        ///delta south
        ///south
        ///south
        ///delta.
        /// </summary>
        internal static string ScriptFile4 {
            get {
                return ResourceManager.GetString("ScriptFile4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north
        ///delta south
        ///west
        ///gamma east
        ///east
        ///gamma west        ///.
        /// </summary>
        internal static string ScriptFile5 {
            get {
                return ResourceManager.GetString("ScriptFile5", resourceCulture);
            }
        }
    }
}
